[package]
name = "enfuse"
version = "0.0.1"
edition = "2024"
description = "Fuse them."
authors = ["potistudio <potistudio@proton.me>"]
license = "MIT"
publish = false

[dependencies]
iced = { version = "0.14.0", features = [
	"canvas",
	"image",
	"advanced",
	"tokio",
] }
rfd = "0.17.2"
rodio = "0.22.2"
symphonia = { version = "0.6.0", features = ["all"] }
tokio = { version = "1.52.3", features = ["full"] }
rayon = "1.12.0"
ringbuf = "0.5.0"
env_logger = "0.11.11"
log = "0.4.33"
rustfft = "6.4.1"
logger = "0.4.0"
midir = "0.11.0"
ort = { version = "2.0.0-rc.13", default-features = true }
ndarray = "0.17"
